### ISSUE TITLE
Support for Gnosis Beacon Chain

### ISSUE THREAD

**Issue by mgarciap** [gobitfly/eth2-beaconchain-explorer-app#126] opened 2022-09-23 00:55 UTC
Could you please add support to the Gnosis Beacon Chain? There is only this dashboard afaik
https://beacon.gnosischain.com/

**Comment by manuelsc** [comment] 2022-09-30 13:27
Duplicate of https://github.com/gobitfly/eth2-beaconchain-explorer-app/issues/92

**Closed by manuelsc** 2022-09-30 13:27 UTC
